apiVersion: v1
kind: Service
metadata:
  name: addressbalance-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: addressbalance
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3333
  selector:
    app: addressbalance
  sessionAffinity: None
